name: CI
on: 
  - push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.5'
      - uses: julia-actions/julia-buildpkg@master
      - run: julia --project run.jl